name: flutter_account_book

repository: https://github.com/KosukeSaigusa/flutter_account_book

packages:
  - packages/**
  - '*'

scripts:
  clean:
    run: melos exec -- "flutter clean"

  pub:get:
    run: melos exec -- "flutter pub get"

  clean:pub:get:
    run: melos exec -- "flutter clean && flutter pub get"

  generate:
    run: melos exec --scope="flutter_account_book" \
      "flutter pub run build_runner build --delete-conflicting-outputs && exit"

  generate:watch:
    run: melos exec --scope="flutter_account_book" \
      "flutter pub run build_runner watch --delete-conflicting-outputs && exit"

  build:dev:ios:
    run: melos exec --scope="flutter_account_book" \
      "fab devios && exit"

  build:prod:ios:
    run: melos exec --scope="flutter_account_book" \
      "fab prodios && exit"

  # build:dev:android:
  #   run: melos exec --scope="flutter_account_book" \
  #     "fab devandroid && exit"

  # build:pro:dandroid:
  #   run: melos exec --scope="mobile" \
  #     "fab prodandroid && exit"

  # build:dev:
  #   run: melos run build:dev:ios && melos run build:dev:android

  # build:prod:
  #   run: melos run build:pro:ios && melos run build:prod:android
