name: flutter_account_book
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cloud_firestore: ^2.5.3
  cloud_functions: ^3.0.4
  connectivity_plus: ^1.0.4
  cupertino_icons: ^1.0.2
  firebase_analytics: ^8.3.3
  firebase_auth: ^3.1.2
  firebase_core: ^1.7.0
  flutter:
    sdk: flutter
  flutter_spinkit: ^5.0.0
  freezed_annotation: ^0.14.2
  gap: ^2.0.0
  keyboard_actions: ^3.4.0
  package_info: ^2.0.2
  shared_preferences: ^2.0.6
  uuid: ^3.0.4

dev_dependencies:
  build_runner: ^2.0.5
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  freezed: ^0.14.2
  json_serializable: ^4.1.3

flutter:
  uses-material-design: true
