// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxsFdBimrrtqJSr5kT-cLPJNSIxUP1bPI',
    appId: '1:1081643100584:web:155b20a2ec976496a9959d',
    messagingSenderId: '1081643100584',
    projectId: 'flutter-account-book',
    authDomain: 'flutter-account-book.firebaseapp.com',
    storageBucket: 'flutter-account-book.appspot.com',
    measurementId: 'G-VK5KS2FP4R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQeji967nADmg0U_EmKtWpc-Zv--kl4hk',
    appId: '1:1081643100584:android:e1c2a02b5e5cce6aa9959d',
    messagingSenderId: '1081643100584',
    projectId: 'flutter-account-book',
    storageBucket: 'flutter-account-book.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPQjfiIRVB0XC0ix6weq56JSjReW3V_aw',
    appId: '1:1081643100584:ios:46e46904d75757f8a9959d',
    messagingSenderId: '1081643100584',
    projectId: 'flutter-account-book',
    storageBucket: 'flutter-account-book.appspot.com',
    iosClientId: '1081643100584-mb66mgmecd7054ufps12mkakt30o8k4f.apps.googleusercontent.com',
    iosBundleId: 'com.kosukesaigusa.flutterAccountBook',
  );
}
