name: flutter_account_book
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.15.0 <3.0.0'

dependencies:
  cloud_firestore:
  cloud_functions:
  connectivity_plus:
  cupertino_icons:
  firebase_analytics:
  firebase_auth:
  firebase_core:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_spinkit:
  flutter_state_notifier:
  freezed_annotation:
  gap:
  google_sign_in:
  intl:
  json_annotation:
  keyboard_actions:
  ks_flutter_commons:
    path: ../ks_flutter_commons
  package_info_plus:
  provider:
  shared_preferences:
  sign_button:
  state_notifier:
  uuid:

dev_dependencies:
  build_runner:
  cloud_firestore_odm_generator:
  flutter_lints:
  flutter_test:
    sdk: flutter
  freezed:
  json_serializable:

flutter:
  uses-material-design: true
