name: flutter_account_book
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.15.0 <3.0.0'

dependencies:
  cloud_firestore: ^3.1.6
  cloud_functions: ^3.2.5
  connectivity_plus: ^2.2.0
  cupertino_icons: ^1.0.2
  firebase_analytics: ^9.0.5
  firebase_auth: ^3.3.5
  firebase_core: ^1.11.0
  flutter:
    sdk: flutter
  flutter_spinkit: ^5.1.0
  flutter_state_notifier: ^0.7.1
  freezed_annotation: ^1.1.0
  gap: ^2.0.0
  google_sign_in: ^5.2.3
  json_annotation: ^4.4.0
  keyboard_actions: ^3.4.6
  ks_flutter_commons:
    path: ../ks_flutter_commons
  package_info_plus: ^1.3.0
  provider: ^6.0.2
  shared_preferences: ^2.0.12
  sign_button: ^2.0.2
  state_notifier: ^0.7.1
  uuid: ^3.0.5

dev_dependencies:
  build_runner: ^2.1.7
  cloud_firestore_odm_generator: ^1.0.0-dev.6
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  # 2021-01-11 時点の最新は 1.1.1 だが
  # analyzer のバージョンを 3.0.0 以上を要求されて
  # firestore_odm の依存関係と矛盾する
  freezed: ^1.1.0
  json_serializable: ^6.1.3

flutter:
  uses-material-design: true
